apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

helmCharts:
- name: istiod
  version: 1.26.2
  repo: https://istio-release.storage.googleapis.com/charts/
  releaseName: istiod
  namespace: istio-system
