apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
namespace: istio-system
helmCharts:
- name: base
  version: 1.26.2
  repo: https://istio-release.storage.googleapis.com/charts/
  releaseName: istio-base
